import { Currency } from 'src/enums/currency.enum';
import { AddressesLevel } from './../enums/addresses.enum';
import { CollectingType } from './../enums/collecting-type.enum';
import { CompanyInvoicesType } from './../enums/company-invoices-type.enum';
import { InvoicesSortingType } from './../enums/invoices-sorting-type';
import { User } from './user.model';

export class Company {
  id: string;
  name: string;
  balance: number;
  phoneNumber: string;
  secondaryPhoneNumber?: string;
  email?: string;
  maxManagersNumber: number;
  maxSupervisorsNumber: number;
  maxCollectorsNumber: number;
  maxCustomersNumber: number;
  managerAccountPrice: number;
  supervisorAccountPrice: number;
  collectorAccountPrice: number;
  currency: Currency;
  collectingType: CollectingType;
  invoicesSortingType: InvoicesSortingType;
  currencySymbol?: string;
  maxLocationLevel: AddressesLevel;
  allowDataImport: boolean;
  addressLevel1Name: string;
  addressLevel2Name: string;
  addressLevel3Name: string;
  addressLevel4Name: string;
  addressLevel5Name: string;
  pricePerCounter: number;
  invoicesType: CompanyInvoicesType;
  createdBy_id?: string;
  parentCompany_id?: string;
  createdBy?: User;
  parentCompany?: Company;
  subCompanies: Company[];
  users: User[];
  // items: Item[];
}
